services:
  app:
    build: .
    container_name: vprofile
    ports:
      - "8080:8080"
    depends_on:
      - db01
      - rmq01
      - mc01
  db01:
    image: mysql:8.0
    container_name: db01
    restart: unless-stopped  
    environment:
      MYSQL_ROOT_PASSWORD: vprodbpass
      MYSQL_DATABASE: accounts
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql:ro

  rmq01:
    image: rabbitmq:3-management
    container_name: rmq01
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  mc01:
    image: memcached:1.6
    container_name: mc01

volumes:
  db_data:
